In [27]:
%tensorflow_version 2.x
import tensorflow as tf

tf.__version__

'2.7.0'

In [22]:
tf.Variable('string', tf.string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'string'>

In [23]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,1,3])
tensor3 = tf.reshape(tensor2, [3, -1])

In [24]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]]

 [[1. 1. 1.]]], shape=(2, 1, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
t = tf.zeros([5,5,5,5])
t